baseURL = 'https://vvnasantosh.net/'
languageCode = 'en-us'

theme = "hugo-PaperMod"

[params]

    colorScheme = "ocean"
    defaultAppearance = "light" # valid options: light or dark
    autoSwitchAppearance = false
    defaultThemeColor = "#007ff"
    ShowBreadCrumbs = true
    ShowToc = true
    math = true
    author= "Varada V N A Santosh"
    description ="ML/AI Engineer"
    homeInfoParams = { Title = "Welcome to My Portfolio", Content = "Explore my ML projects, Jupyter notebooks, and AI concepts." }

 [params.profileMode]

    enabled = true
    title = "Varada V N A Santosh"


    imageWidth = 120
    imageHeight = 120
   
     [[params.profileMode.buttons]] 
      name = "Blog"
      url = "/posts/"
    
